
glmestats = fitglme(trainingTable,'maxCortDelta ~ 1 + behavState')
glmestats = fitglme(trainingTable,'maxCortTheta ~ 1 + behavState')
glmestats = fitglme(trainingTable,'maxCortAlpha ~ 1 + behavState')
glmestats = fitglme(trainingTable,'maxCortBeta ~ 1 + behavState')
glmestats = fitglme(trainingTable,'maxCortGamma ~ 1 + behavState')
glmestats = fitglme(trainingTable,'maxHippTheta ~ 1 + behavState')
glmestats = fitglme(trainingTable,'numWhiskEvents ~ 1 + behavState')
glmestats = fitglme(trainingTable,'avgEMG ~ 1 + behavState')

trainingTable.maxCortThetaAlpha = trainingTable.maxCortTheta-trainingTable.maxCortAlpha;
glmestats = fitglme(trainingTable,'maxCortThetaAlpha ~ 1 + behavState')
glmestats = fitglme(trainingTable,'meanMDiameter ~ 1 + behavState')
glmestats = fitglme(trainingTable,'varMDiameter ~ 1 + behavState')
glmestats = fitglme(trainingTable,'meanZDiameter ~ 1 + behavState')
glmestats = fitglme(trainingTable,'varZDiameter ~ 1 + behavState')
glmestats = fitglme(trainingTable,'minMDiameter ~ 1 + behavState')
glmestats = fitglme(trainingTable,'minZDiameter ~ 1 + behavState')
glmestats = fitglme(trainingTable,'sumEyeMotion ~ 1 + behavState')
glmestats = fitglme(trainingTable,'varEyeMotion ~ 1 + behavState')
glmestats = fitglme(trainingTable,'meanCentroidX ~ 1 + behavState')
glmestats = fitglme(trainingTable,'meanCentroidY ~ 1 + behavState')
glmestats = fitglme(trainingTable,'maxCentroidX ~ 1 + behavState')
glmestats = fitglme(trainingTable,'maxCentroidY ~ 1 + behavState')
glmestats = fitglme(trainingTable,'varCentroidX ~ 1 + behavState')
glmestats = fitglme(trainingTable,'varCentroidY ~ 1 + behavState')