function [] = Fig_MeanGFP_POOLED_RAW_AcrossDays_WaterVsAlcohol_SST_project(rootFolder,saveState,delim)
%________________________________________________________________________________________________________________________
% Written by Julio Flores-Cuadra
% The Pennsylvania State University, Dept. of Biology
%
% Acknowledgments. This code was adapted from scripts wrote by Dr. Kevin
% Turner and MD Shakhawat Hossain
%________________________________________________________________________________________________________________________

%% set-up and process data
%  am pretty sure I can add a loop here for the GFP, CBV and Behavioral
%  data. Think about this later 
path = [rootFolder delim 'Results_SST_project']; % Path to the folder containing Results_SleepData.mat
cd(path)
resultsStruct_GFP = 'Results_MeanGFP';
load(resultsStruct_GFP)

%Path =
%Results_MeanGFP.group.day.animalID.signal.behavior.GFP.hemisphere 

groups = {'Water', 'Alcohol'};
days = {'Day1', 'Day2', 'Day3', 'Day4', 'Day5', 'Day6'};
behavior = {'Rest', 'Whisk', 'Stim', 'NREM', 'REM'};
hemisphere = {'MeanNE', 'MeanACh'}; % NE is PFC and ACh is S1BF

%% Store the data you need for the analysis
% Loop through groups

for ee = 1:length(groups)
    currentGroup = groups{ee};

    for hemi = 1:length(hemisphere)
        currentHemisphere = hemisphere{hemi};

        % Loop through days
        for xx = 1:length(days)
            currentDay = days{xx};

            % Check if this group actually has data for this day
            if ~isfield(Results_MeanGFP.(currentGroup), currentDay)
                continue
            end

            FPanimalIDs = fieldnames(Results_MeanGFP.(currentGroup).(currentDay));
            if isempty(FPanimalIDs)
                continue
            end

            for aa = 1:length(FPanimalIDs)
                animalID = FPanimalIDs{aa};

                % Loop through animals for this (group,day)
                for behavi = 1:length(behavior)
                    currentBehavior = behavior{behavi};

                    if ~isfield(Results_MeanGFP.(currentGroup).(currentDay).(animalID).MeanGFP, currentBehavior)
                        continue
                    end

                    %Calculate the mean of all events within one mouse
                    rawEvents = Results_MeanGFP.(currentGroup).(currentDay).(animalID).MeanGFP.(currentBehavior).GFP.(currentHemisphere);
                    mouseMean = mean(rawEvents,1); %k<AGROw>

                    %store the mean for plotting later
                    data.(currentGroup).(currentDay).(animalID).MeanGFP.(currentHemisphere).([currentBehavior '_Events']) =  rawEvents;
                    data.(currentGroup).(currentDay).(animalID).MeanGFP.(currentHemisphere).([currentBehavior '_Mean'])  =  mouseMean;
                end
            end
        end
    end
end
%% Calculate group-level means and SEM across mice for each day, behavior, and hemisphere
for hemi = 1:length(hemisphere)
    currentHemisphere = hemisphere{hemi};

    for behavi = 1:length(behavior)
        currentBehavior = behavior{behavi};

        for ee = 1:length(groups)
            currentGroup = groups{ee};

            for xx = 1:length(days)
                currentDay = days{xx};

                if ~isfield(data.(currentGroup), currentDay)
                    continue
                end

                FPanimalIDs = fieldnames(data.(currentGroup).(currentDay));
                FPanimalIDs = setdiff(FPanimalIDs, {'GroupStats'}); % exclude GroupStats from the list. I do not know why is is taking it as variable :( in the debug mode it does not happen 
                if isempty(FPanimalIDs)
                    continue
                end

                allEvents = [];

                for aa = 1:length(FPanimalIDs)
                    animalID = FPanimalIDs{aa};

                    if isfield(data.(currentGroup).(currentDay).(animalID).MeanGFP.(currentHemisphere), [currentBehavior '_Events'])
                        events = data.(currentGroup).(currentDay).(animalID).MeanGFP.(currentHemisphere).([currentBehavior '_Events']);
                        allEvents = [allEvents; events(:)]; % pooled across animals
                    end
                end

                if ~isempty(allEvents)
                    data.(currentGroup).(currentDay).GroupStats.(currentHemisphere).([currentBehavior '_PooledMean']) = mean(allEvents);
                    data.(currentGroup).(currentDay).GroupStats.(currentHemisphere).([currentBehavior '_PooledSEM'])  = std(allEvents)/sqrt(length(allEvents));
                else
                    data.(currentGroup).(currentDay).GroupStats.(currentHemisphere).([currentBehavior '_PooledMean']) = NaN;
                    data.(currentGroup).(currentDay).GroupStats.(currentHemisphere).([currentBehavior '_PooledSEM'])  = NaN;
                end

            end
        end
    end
end




% Define shared parameters
days = {'Day1', 'Day2', 'Day3', 'Day4', 'Day5', 'Day6'};
waterColor = [0 0 0];
alcoholColor = [0.8667, 0.1098, 0.4667];

%% ============ FIGURE 1: PFC (MeanNE) =============
currentHemisphere = 'MeanNE';
figure('Name','PFC - MeanNE');

% ------------------ REST ------------------
subplot(2,3,1); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanNE.Rest_PooledMean, data.Water.Day2.GroupStats.MeanNE.Rest_PooledMean, ...
     data.Water.Day3.GroupStats.MeanNE.Rest_PooledMean, data.Water.Day4.GroupStats.MeanNE.Rest_PooledMean, ...
     data.Water.Day5.GroupStats.MeanNE.Rest_PooledMean, data.Water.Day6.GroupStats.MeanNE.Rest_PooledMean], ...
    [data.Water.Day1.GroupStats.MeanNE.Rest_PooledSEM, data.Water.Day2.GroupStats.MeanNE.Rest_PooledSEM, ...
     data.Water.Day3.GroupStats.MeanNE.Rest_PooledSEM, data.Water.Day4.GroupStats.MeanNE.Rest_PooledSEM, ...
     data.Water.Day5.GroupStats.MeanNE.Rest_PooledSEM, data.Water.Day6.GroupStats.MeanNE.Rest_PooledSEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanNE.Rest_PooledMean, data.Alcohol.Day2.GroupStats.MeanNE.Rest_PooledMean, ...
     data.Alcohol.Day3.GroupStats.MeanNE.Rest_PooledMean, data.Alcohol.Day4.GroupStats.MeanNE.Rest_PooledMean, ...
     data.Alcohol.Day5.GroupStats.MeanNE.Rest_PooledMean, data.Alcohol.Day6.GroupStats.MeanNE.Rest_PooledMean], ...
    [data.Alcohol.Day1.GroupStats.MeanNE.Rest_PooledSEM, data.Alcohol.Day2.GroupStats.MeanNE.Rest_PooledSEM, ...
     data.Alcohol.Day3.GroupStats.MeanNE.Rest_PooledSEM, data.Alcohol.Day4.GroupStats.MeanNE.Rest_PooledSEM, ...
     data.Alcohol.Day5.GroupStats.MeanNE.Rest_PooledSEM, data.Alcohol.Day6.GroupStats.MeanNE.Rest_PooledSEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('Rest - PFC'); xticks(1:6); xticklabels(days); ylabel('Mean GFP');
xlim([0.5 6.5])

% ------------------ WHISK ------------------
subplot(2,3,2); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanNE.Whisk_PooledMean, data.Water.Day2.GroupStats.MeanNE.Whisk_PooledMean, ...
     data.Water.Day3.GroupStats.MeanNE.Whisk_PooledMean, data.Water.Day4.GroupStats.MeanNE.Whisk_PooledMean, ...
     data.Water.Day5.GroupStats.MeanNE.Whisk_PooledMean, data.Water.Day6.GroupStats.MeanNE.Whisk_PooledMean], ...
    [data.Water.Day1.GroupStats.MeanNE.Whisk_PooledSEM, data.Water.Day2.GroupStats.MeanNE.Whisk_PooledSEM, ...
     data.Water.Day3.GroupStats.MeanNE.Whisk_PooledSEM, data.Water.Day4.GroupStats.MeanNE.Whisk_PooledSEM, ...
     data.Water.Day5.GroupStats.MeanNE.Whisk_PooledSEM, data.Water.Day6.GroupStats.MeanNE.Whisk_PooledSEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanNE.Whisk_PooledMean, data.Alcohol.Day2.GroupStats.MeanNE.Whisk_PooledMean, ...
     data.Alcohol.Day3.GroupStats.MeanNE.Whisk_PooledMean, data.Alcohol.Day4.GroupStats.MeanNE.Whisk_PooledMean, ...
     data.Alcohol.Day5.GroupStats.MeanNE.Whisk_PooledMean, data.Alcohol.Day6.GroupStats.MeanNE.Whisk_PooledMean], ...
    [data.Alcohol.Day1.GroupStats.MeanNE.Whisk_PooledSEM, data.Alcohol.Day2.GroupStats.MeanNE.Whisk_PooledSEM, ...
     data.Alcohol.Day3.GroupStats.MeanNE.Whisk_PooledSEM, data.Alcohol.Day4.GroupStats.MeanNE.Whisk_PooledSEM, ...
     data.Alcohol.Day5.GroupStats.MeanNE.Whisk_PooledSEM, data.Alcohol.Day6.GroupStats.MeanNE.Whisk_PooledSEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('Whisk - PFC'); xticks(1:6); xticklabels(days); ylabel('Mean GFP');
xlim([0.5 6.5])

% ------------------ STIM ------------------
subplot(2,3,3); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanNE.Stim_PooledMean, data.Water.Day2.GroupStats.MeanNE.Stim_PooledMean, ...
     data.Water.Day3.GroupStats.MeanNE.Stim_PooledMean, data.Water.Day4.GroupStats.MeanNE.Stim_PooledMean, ...
     data.Water.Day5.GroupStats.MeanNE.Stim_PooledMean, data.Water.Day6.GroupStats.MeanNE.Stim_PooledMean], ...
    [data.Water.Day1.GroupStats.MeanNE.Stim_PooledSEM, data.Water.Day2.GroupStats.MeanNE.Stim_PooledSEM, ...
     data.Water.Day3.GroupStats.MeanNE.Stim_PooledSEM, data.Water.Day4.GroupStats.MeanNE.Stim_PooledSEM, ...
     data.Water.Day5.GroupStats.MeanNE.Stim_PooledSEM, data.Water.Day6.GroupStats.MeanNE.Stim_PooledSEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanNE.Stim_PooledMean, data.Alcohol.Day2.GroupStats.MeanNE.Stim_PooledMean, ...
     data.Alcohol.Day3.GroupStats.MeanNE.Stim_PooledMean, data.Alcohol.Day4.GroupStats.MeanNE.Stim_PooledMean, ...
     data.Alcohol.Day5.GroupStats.MeanNE.Stim_PooledMean, data.Alcohol.Day6.GroupStats.MeanNE.Stim_PooledMean], ...
    [data.Alcohol.Day1.GroupStats.MeanNE.Stim_PooledSEM, data.Alcohol.Day2.GroupStats.MeanNE.Stim_PooledSEM, ...
     data.Alcohol.Day3.GroupStats.MeanNE.Stim_PooledSEM, data.Alcohol.Day4.GroupStats.MeanNE.Stim_PooledSEM, ...
     data.Alcohol.Day5.GroupStats.MeanNE.Stim_PooledSEM, data.Alcohol.Day6.GroupStats.MeanNE.Stim_PooledSEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('Stim - PFC'); xticks(1:6); xticklabels(days); ylabel('Mean GFP');
xlim([0.5 6.5])

% ------------------ NREM ------------------
subplot(2,3,4); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanNE.NREM_PooledMean, data.Water.Day2.GroupStats.MeanNE.NREM_PooledMean, ...
     data.Water.Day3.GroupStats.MeanNE.NREM_PooledMean, data.Water.Day4.GroupStats.MeanNE.NREM_PooledMean, ...
     data.Water.Day5.GroupStats.MeanNE.NREM_PooledMean, data.Water.Day6.GroupStats.MeanNE.NREM_PooledMean], ...
    [data.Water.Day1.GroupStats.MeanNE.NREM_PooledSEM, data.Water.Day2.GroupStats.MeanNE.NREM_PooledSEM, ...
     data.Water.Day3.GroupStats.MeanNE.NREM_PooledSEM, data.Water.Day4.GroupStats.MeanNE.NREM_PooledSEM, ...
     data.Water.Day5.GroupStats.MeanNE.NREM_PooledSEM, data.Water.Day6.GroupStats.MeanNE.NREM_PooledSEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanNE.NREM_PooledMean, data.Alcohol.Day2.GroupStats.MeanNE.NREM_PooledMean, ...
     data.Alcohol.Day3.GroupStats.MeanNE.NREM_PooledMean, data.Alcohol.Day4.GroupStats.MeanNE.NREM_PooledMean, ...
     data.Alcohol.Day5.GroupStats.MeanNE.NREM_PooledMean, data.Alcohol.Day6.GroupStats.MeanNE.NREM_PooledMean], ...
    [data.Alcohol.Day1.GroupStats.MeanNE.NREM_PooledSEM, data.Alcohol.Day2.GroupStats.MeanNE.NREM_PooledSEM, ...
     data.Alcohol.Day3.GroupStats.MeanNE.NREM_PooledSEM, data.Alcohol.Day4.GroupStats.MeanNE.NREM_PooledSEM, ...
     data.Alcohol.Day5.GroupStats.MeanNE.NREM_PooledSEM, data.Alcohol.Day6.GroupStats.MeanNE.NREM_PooledSEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('NREM - PFC'); xticks(1:6); xticklabels(days); ylabel('Mean GFP'); 
xlim([0.5 6.5])

% ------------------ REM ------------------
subplot(2,3,5); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanNE.REM_PooledMean, data.Water.Day2.GroupStats.MeanNE.REM_PooledMean, ...
     data.Water.Day3.GroupStats.MeanNE.REM_PooledMean, data.Water.Day4.GroupStats.MeanNE.REM_PooledMean, ...
     data.Water.Day5.GroupStats.MeanNE.REM_PooledMean, data.Water.Day6.GroupStats.MeanNE.REM_PooledMean], ...
    [data.Water.Day1.GroupStats.MeanNE.REM_PooledSEM, data.Water.Day2.GroupStats.MeanNE.REM_PooledSEM, ...
     data.Water.Day3.GroupStats.MeanNE.REM_PooledSEM, data.Water.Day4.GroupStats.MeanNE.REM_PooledSEM, ...
     data.Water.Day5.GroupStats.MeanNE.REM_PooledSEM, data.Water.Day6.GroupStats.MeanNE.REM_PooledSEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanNE.REM_PooledMean, data.Alcohol.Day2.GroupStats.MeanNE.REM_PooledMean, ...
     data.Alcohol.Day3.GroupStats.MeanNE.REM_PooledMean, data.Alcohol.Day4.GroupStats.MeanNE.REM_PooledMean, ...
     data.Alcohol.Day5.GroupStats.MeanNE.REM_PooledMean, data.Alcohol.Day6.GroupStats.MeanNE.REM_PooledMean], ...
    [data.Alcohol.Day1.GroupStats.MeanNE.REM_PooledSEM, data.Alcohol.Day2.GroupStats.MeanNE.REM_PooledSEM, ...
     data.Alcohol.Day3.GroupStats.MeanNE.REM_PooledSEM, data.Alcohol.Day4.GroupStats.MeanNE.REM_PooledSEM, ...
     data.Alcohol.Day5.GroupStats.MeanNE.REM_PooledSEM, data.Alcohol.Day6.GroupStats.MeanNE.REM_PooledSEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('REM - PFC'); xticks(1:6); xticklabels(days); ylabel('Mean GFP'); 
xlim([0.5 6.5])

sgtitle('PFC (MeanNE) - Water vs Alcohol - All Behaviors');
legend({'Water','Alcohol'}, 'Location','bestoutside');
%% ============ FIGURE 2: S1BF (MeanACh) =============
currentHemisphere = 'MeanACh';
figure('Name','S1BF - MeanACh');

% ------------------ REST ------------------
subplot(2,3,1); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanACh.Rest_PooledMean, data.Water.Day2.GroupStats.MeanACh.Rest_PooledMean, ...
     data.Water.Day3.GroupStats.MeanACh.Rest_PooledMean, data.Water.Day4.GroupStats.MeanACh.Rest_PooledMean, ...
     data.Water.Day5.GroupStats.MeanACh.Rest_PooledMean, data.Water.Day6.GroupStats.MeanACh.Rest_PooledMean], ...
    [data.Water.Day1.GroupStats.MeanACh.Rest_PooledSEM, data.Water.Day2.GroupStats.MeanACh.Rest_PooledSEM, ...
     data.Water.Day3.GroupStats.MeanACh.Rest_PooledSEM, data.Water.Day4.GroupStats.MeanACh.Rest_PooledSEM, ...
     data.Water.Day5.GroupStats.MeanACh.Rest_PooledSEM, data.Water.Day6.GroupStats.MeanACh.Rest_PooledSEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanACh.Rest_PooledMean, data.Alcohol.Day2.GroupStats.MeanACh.Rest_PooledMean, ...
     data.Alcohol.Day3.GroupStats.MeanACh.Rest_PooledMean, data.Alcohol.Day4.GroupStats.MeanACh.Rest_PooledMean, ...
     data.Alcohol.Day5.GroupStats.MeanACh.Rest_PooledMean, data.Alcohol.Day6.GroupStats.MeanACh.Rest_PooledMean], ...
    [data.Alcohol.Day1.GroupStats.MeanACh.Rest_PooledSEM, data.Alcohol.Day2.GroupStats.MeanACh.Rest_PooledSEM, ...
     data.Alcohol.Day3.GroupStats.MeanACh.Rest_PooledSEM, data.Alcohol.Day4.GroupStats.MeanACh.Rest_PooledSEM, ...
     data.Alcohol.Day5.GroupStats.MeanACh.Rest_PooledSEM, data.Alcohol.Day6.GroupStats.MeanACh.Rest_PooledSEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('Rest - S1BF'); xticks(1:6); xticklabels(days); ylabel('Mean GFP');
xlim([0.5 6.5])

% ------------------ WHISK ------------------
subplot(2,3,2); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanACh.Whisk_PooledMean, data.Water.Day2.GroupStats.MeanACh.Whisk_PooledMean, ...
     data.Water.Day3.GroupStats.MeanACh.Whisk_PooledMean, data.Water.Day4.GroupStats.MeanACh.Whisk_PooledMean, ...
     data.Water.Day5.GroupStats.MeanACh.Whisk_PooledMean, data.Water.Day6.GroupStats.MeanACh.Whisk_PooledMean], ...
    [data.Water.Day1.GroupStats.MeanACh.Whisk_PooledSEM, data.Water.Day2.GroupStats.MeanACh.Whisk_PooledSEM, ...
     data.Water.Day3.GroupStats.MeanACh.Whisk_PooledSEM, data.Water.Day4.GroupStats.MeanACh.Whisk_PooledSEM, ...
     data.Water.Day5.GroupStats.MeanACh.Whisk_PooledSEM, data.Water.Day6.GroupStats.MeanACh.Whisk_PooledSEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanACh.Whisk_PooledMean, data.Alcohol.Day2.GroupStats.MeanACh.Whisk_PooledMean, ...
     data.Alcohol.Day3.GroupStats.MeanACh.Whisk_PooledMean, data.Alcohol.Day4.GroupStats.MeanACh.Whisk_PooledMean, ...
     data.Alcohol.Day5.GroupStats.MeanACh.Whisk_PooledMean, data.Alcohol.Day6.GroupStats.MeanACh.Whisk_PooledMean], ...
    [data.Alcohol.Day1.GroupStats.MeanACh.Whisk_PooledSEM, data.Alcohol.Day2.GroupStats.MeanACh.Whisk_PooledSEM, ...
     data.Alcohol.Day3.GroupStats.MeanACh.Whisk_PooledSEM, data.Alcohol.Day4.GroupStats.MeanACh.Whisk_PooledSEM, ...
     data.Alcohol.Day5.GroupStats.MeanACh.Whisk_PooledSEM, data.Alcohol.Day6.GroupStats.MeanACh.Whisk_PooledSEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('Whisk - S1BF'); xticks(1:6); xticklabels(days); ylabel('Mean GFP');
xlim([0.5 6.5])

% ------------------ STIM ------------------
subplot(2,3,3); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanACh.Stim_PooledMean, data.Water.Day2.GroupStats.MeanACh.Stim_PooledMean, ...
     data.Water.Day3.GroupStats.MeanACh.Stim_PooledMean, data.Water.Day4.GroupStats.MeanACh.Stim_PooledMean, ...
     data.Water.Day5.GroupStats.MeanACh.Stim_PooledMean, data.Water.Day6.GroupStats.MeanACh.Stim_PooledMean], ...
    [data.Water.Day1.GroupStats.MeanACh.Stim_PooledSEM, data.Water.Day2.GroupStats.MeanACh.Stim_PooledSEM, ...
     data.Water.Day3.GroupStats.MeanACh.Stim_PooledSEM, data.Water.Day4.GroupStats.MeanACh.Stim_PooledSEM, ...
     data.Water.Day5.GroupStats.MeanACh.Stim_PooledSEM, data.Water.Day6.GroupStats.MeanACh.Stim_PooledSEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanACh.Stim_PooledMean, data.Alcohol.Day2.GroupStats.MeanACh.Stim_PooledMean, ...
     data.Alcohol.Day3.GroupStats.MeanACh.Stim_PooledMean, data.Alcohol.Day4.GroupStats.MeanACh.Stim_PooledMean, ...
     data.Alcohol.Day5.GroupStats.MeanACh.Stim_PooledMean, data.Alcohol.Day6.GroupStats.MeanACh.Stim_PooledMean], ...
    [data.Alcohol.Day1.GroupStats.MeanACh.Stim_PooledSEM, data.Alcohol.Day2.GroupStats.MeanACh.Stim_PooledSEM, ...
     data.Alcohol.Day3.GroupStats.MeanACh.Stim_PooledSEM, data.Alcohol.Day4.GroupStats.MeanACh.Stim_PooledSEM, ...
     data.Alcohol.Day5.GroupStats.MeanACh.Stim_PooledSEM, data.Alcohol.Day6.GroupStats.MeanACh.Stim_PooledSEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('Stim - S1BF'); xticks(1:6); xticklabels(days); ylabel('Mean GFP'); 
xlim([0.5 6.5])

% ------------------ NREM ------------------
subplot(2,3,4); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanACh.NREM_PooledMean, data.Water.Day2.GroupStats.MeanACh.NREM_PooledMean, ...
     data.Water.Day3.GroupStats.MeanACh.NREM_PooledMean, data.Water.Day4.GroupStats.MeanACh.NREM_PooledMean, ...
     data.Water.Day5.GroupStats.MeanACh.NREM_PooledMean, data.Water.Day6.GroupStats.MeanACh.NREM_PooledMean], ...
    [data.Water.Day1.GroupStats.MeanACh.NREM_PooledSEM, data.Water.Day2.GroupStats.MeanACh.NREM_PooledSEM, ...
     data.Water.Day3.GroupStats.MeanACh.NREM_PooledSEM, data.Water.Day4.GroupStats.MeanACh.NREM_PooledSEM, ...
     data.Water.Day5.GroupStats.MeanACh.NREM_PooledSEM, data.Water.Day6.GroupStats.MeanACh.NREM_PooledSEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanACh.NREM_PooledMean, data.Alcohol.Day2.GroupStats.MeanACh.NREM_PooledMean, ...
     data.Alcohol.Day3.GroupStats.MeanACh.NREM_PooledMean, data.Alcohol.Day4.GroupStats.MeanACh.NREM_PooledMean, ...
     data.Alcohol.Day5.GroupStats.MeanACh.NREM_PooledMean, data.Alcohol.Day6.GroupStats.MeanACh.NREM_PooledMean], ...
    [data.Alcohol.Day1.GroupStats.MeanACh.NREM_PooledSEM, data.Alcohol.Day2.GroupStats.MeanACh.NREM_PooledSEM, ...
     data.Alcohol.Day3.GroupStats.MeanACh.NREM_PooledSEM, data.Alcohol.Day4.GroupStats.MeanACh.NREM_PooledSEM, ...
     data.Alcohol.Day5.GroupStats.MeanACh.NREM_PooledSEM, data.Alcohol.Day6.GroupStats.MeanACh.NREM_PooledSEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('NREM - S1BF'); xticks(1:6); xticklabels(days); ylabel('Mean GFP');
xlim([0.5 6.5])

% ------------------ REM ------------------
subplot(2,3,5); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanACh.REM_PooledMean, data.Water.Day2.GroupStats.MeanACh.REM_PooledMean, ...
     data.Water.Day3.GroupStats.MeanACh.REM_PooledMean, data.Water.Day4.GroupStats.MeanACh.REM_PooledMean, ...
     data.Water.Day5.GroupStats.MeanACh.REM_PooledMean, data.Water.Day6.GroupStats.MeanACh.REM_PooledMean], ...
    [data.Water.Day1.GroupStats.MeanACh.REM_PooledSEM, data.Water.Day2.GroupStats.MeanACh.REM_PooledSEM, ...
     data.Water.Day3.GroupStats.MeanACh.REM_PooledSEM, data.Water.Day4.GroupStats.MeanACh.REM_PooledSEM, ...
     data.Water.Day5.GroupStats.MeanACh.REM_PooledSEM, data.Water.Day6.GroupStats.MeanACh.REM_PooledSEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanACh.REM_PooledMean, data.Alcohol.Day2.GroupStats.MeanACh.REM_PooledMean, ...
     data.Alcohol.Day3.GroupStats.MeanACh.REM_PooledMean, data.Alcohol.Day4.GroupStats.MeanACh.REM_PooledMean, ...
     data.Alcohol.Day5.GroupStats.MeanACh.REM_PooledMean, data.Alcohol.Day6.GroupStats.MeanACh.REM_PooledMean], ...
    [data.Alcohol.Day1.GroupStats.MeanACh.REM_PooledSEM, data.Alcohol.Day2.GroupStats.MeanACh.REM_PooledSEM, ...
     data.Alcohol.Day3.GroupStats.MeanACh.REM_PooledSEM, data.Alcohol.Day4.GroupStats.MeanACh.REM_PooledSEM, ...
     data.Alcohol.Day5.GroupStats.MeanACh.REM_PooledSEM, data.Alcohol.Day6.GroupStats.MeanACh.REM_PooledSEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('REM - S1BF'); xticks(1:6); xticklabels(days); ylabel('Mean GFP');
xlim([0.5 6.5])

sgtitle('S1BF SST - Water vs Alcohol - All Behaviors');


%% ============ FIGURE: PFC (MeanNE) - All Behaviors - Group + Individual ============
currentHemisphere = 'MeanNE';
behaviorList = {'Rest','Whisk','Stim','NREM','REM'};
days = {'Day1','Day2','Day3','Day4','Day5','Day6'};
x = 1:6;
xOffset = 0.15;

figure('Name','PFC - MeanNE - All Behaviors - Group + pooled day events of each animmal');

for b = 1:length(behaviorList)
    currentBehavior = behaviorList{b};
    subplot(2,3,b); hold on;
    
    % ---------- BAR: Water group mean ----------
    bar(x - xOffset, ...
        [data.Water.Day1.GroupStats.(currentHemisphere).([currentBehavior '_PooledMean']), ...
         data.Water.Day2.GroupStats.(currentHemisphere).([currentBehavior '_PooledMean']), ...
         data.Water.Day3.GroupStats.(currentHemisphere).([currentBehavior '_PooledMean']), ...
         data.Water.Day4.GroupStats.(currentHemisphere).([currentBehavior '_PooledMean']), ...
         data.Water.Day5.GroupStats.(currentHemisphere).([currentBehavior '_PooledMean']), ...
         data.Water.Day6.GroupStats.(currentHemisphere).([currentBehavior '_PooledMean'])], ...
         0.3, 'FaceColor', waterColor, 'EdgeColor', 'none');
     
    % ---------- BAR: Alcohol group mean ----------
    bar(x + xOffset, ...
        [data.Alcohol.Day1.GroupStats.(currentHemisphere).([currentBehavior '_PooledMean']), ...
         data.Alcohol.Day2.GroupStats.(currentHemisphere).([currentBehavior '_PooledMean']), ...
         data.Alcohol.Day3.GroupStats.(currentHemisphere).([currentBehavior '_PooledMean']), ...
         data.Alcohol.Day4.GroupStats.(currentHemisphere).([currentBehavior '_PooledMean']), ...
         data.Alcohol.Day5.GroupStats.(currentHemisphere).([currentBehavior '_PooledMean']), ...
         data.Alcohol.Day6.GroupStats.(currentHemisphere).([currentBehavior '_PooledMean'])], ...
         0.3, 'FaceColor', alcoholColor, 'EdgeColor', 'none');

    % ---------- SCATTER: Water individual mice ----------
    for d = 1:6
        mouseIDs = fieldnames(data.Water.(days{d}));
        mouseIDs(strcmp(mouseIDs,'GroupStats')) = [];
        values = [];
        for aa = 1:length(mouseIDs)
            if isfield(data.Water.(days{d}).(mouseIDs{aa}).MeanGFP.(currentHemisphere), [currentBehavior '_PooledMean'])
                values(end+1) = data.Water.(days{d}).(mouseIDs{aa}).MeanGFP.(currentHemisphere).([currentBehavior '_PooledMean']);
            end
        end
        scatter(repmat(d - xOffset, 1, length(values)), values, 40, 'r', 'filled', 'jitter', 'on', 'jitterAmount', 0.1);
    end

    % ---------- SCATTER: Alcohol individual mice ----------
    for d = 1:6
        mouseIDs = fieldnames(data.Alcohol.(days{d}));
        mouseIDs(strcmp(mouseIDs,'GroupStats')) = [];
        values = [];
        for aa = 1:length(mouseIDs)
            if isfield(data.Alcohol.(days{d}).(mouseIDs{aa}).MeanGFP.(currentHemisphere), [currentBehavior '_PooledMean'])
                values(end+1) = data.Alcohol.(days{d}).(mouseIDs{aa}).MeanGFP.(currentHemisphere).([currentBehavior '_PooledMean']);
            end
        end
        scatter(repmat(d + xOffset, 1, length(values)), values, 40, [0.6 0.6 0.6], 'filled', 'jitter', 'on', 'jitterAmount', 0.1);
    end

    title([currentBehavior ' - PFC']);
    xticks(1:6);
    xticklabels({'BL','DID1','DID2','DID3','DID4','Post-alcohol'});
    ylabel('Mean GFP (%)');
    xlim([0.5 6.5])
end

sgtitle('PFC - MeanNE - All Behaviors - Group + Individual');
legend({'Water mean','Alcohol mean'}, 'Location','bestoutside');


end 