function [] = Fig_MeanGFP_RAW_AcrossDays_WaterVsAlcohol_SST_project(rootFolder,saveState,delim)
%________________________________________________________________________________________________________________________
% Written by Julio Flores-Cuadra
% The Pennsylvania State University, Dept. of Biology
%
% Acknowledgments. This code was adapted from scripts wrote by Dr. Kevin
% Turner and MD Shakhawat Hossain
%________________________________________________________________________________________________________________________

%% set-up and process data
path = [rootFolder delim 'Results_SST_project']; % Path to the folder containing Results_SleepData.mat
cd(path)
resultsStruct_GFP = 'Results_MeanGFP';
load(resultsStruct_GFP)

%Path =
%Results_MeanGFP.group.day.animalID.signal.behavior.GFP.hemisphere 

groups = {'Water', 'Alcohol'};
days = {'Day1', 'Day2', 'Day3', 'Day4', 'Day5', 'Day6'};
behavior = {'Rest', 'Whisk', 'Stim', 'NREM', 'REM'};
hemisphere = {'MeanNE', 'MeanACh'}; % NE is PFC and ACh is S1BF

%% Store the data you need for the analysis
% Loop through groups

for ee = 1:length(groups)
    currentGroup = groups{ee};

    for hemi = 1:length(hemisphere)
        currentHemisphere = hemisphere{hemi};

        % Loop through days
        for xx = 1:length(days)
            currentDay = days{xx};

            % Check if this group actually has data for this day
            if ~isfield(Results_MeanGFP.(currentGroup), currentDay)
                continue
            end

            FPanimalIDs = fieldnames(Results_MeanGFP.(currentGroup).(currentDay));
            if isempty(FPanimalIDs)
                continue
            end

            for aa = 1:length(FPanimalIDs)
                animalID = FPanimalIDs{aa};

                % Loop through animals for this (group,day)
                for behavi = 1:length(behavior)
                    currentBehavior = behavior{behavi};

                    if ~isfield(Results_MeanGFP.(currentGroup).(currentDay).(animalID).MeanGFP, currentBehavior)
                        continue
                    end

                    %Calculate the mean of all events within one mouse
                    rawEvents = Results_MeanGFP.(currentGroup).(currentDay).(animalID).MeanGFP.(currentBehavior).GFP.(currentHemisphere);
                    mouseMean = mean(rawEvents,1); %k<AGROw>

                    %store the mean for plotting later
                    data.(currentGroup).(currentDay).(animalID).MeanGFP.(currentHemisphere).([currentBehavior '_Events']) =  rawEvents;
                    data.(currentGroup).(currentDay).(animalID).MeanGFP.(currentHemisphere).([currentBehavior '_Mean'])  =  mouseMean;
                end
            end
        end
    end
end
%% Calculate group-level means and SEM across mice for each day, behavior, and hemisphere
for hemi = 1:length(hemisphere)
    currentHemisphere = hemisphere{hemi};

    for behavi = 1:length(behavior)
        currentBehavior = behavior{behavi};

        for ee = 1:length(groups)
            currentGroup = groups{ee};

            for xx = 1:length(days)
                currentDay = days{xx};

                if ~isfield(data.(currentGroup), currentDay)
                    continue
                end

                FPanimalIDs = fieldnames(data.(currentGroup).(currentDay));
                FPanimalIDs = setdiff(FPanimalIDs, {'GroupStats'}); % exclude GroupStats from the list. I do not know why is is taking it as variable :( in the debug mode it does not happen 
                if isempty(FPanimalIDs)
                    continue
                end

                mouseMeans = [];

                for aa = 1:length(FPanimalIDs)
                    animalID = FPanimalIDs{aa};

                    if isfield(data.(currentGroup).(currentDay).(animalID).MeanGFP.(currentHemisphere), [currentBehavior '_Mean'])
                        currentMean = data.(currentGroup).(currentDay).(animalID).MeanGFP.(currentHemisphere).([currentBehavior '_Mean']);
                        mouseMeans(end+1) = currentMean; %#ok<AGROW>
                    end
                end
                
                if ~isempty(mouseMeans)
                    data.(currentGroup).(currentDay).GroupStats.(currentHemisphere).([currentBehavior '_Mean']) = nanmean(mouseMeans);
                    data.(currentGroup).(currentDay).GroupStats.(currentHemisphere).([currentBehavior '_SEM'])  = nanstd(mouseMeans)/sqrt(sum(~isnan(mouseMeans)));
                else
                    data.(currentGroup).(currentDay).GroupStats.(currentHemisphere).([currentBehavior '_Mean']) = NaN;
                    data.(currentGroup).(currentDay).GroupStats.(currentHemisphere).([currentBehavior '_SEM'])  = NaN;
                end

            end
        end
    end
end



% Define shared parameters
days = {'BL', 'DID1', 'DID2', 'DID3', 'DID4', 'Post-alcohol'};
waterColor = [0 0 0];
alcoholColor = [0.8667, 0.1098, 0.4667];

%% Figure 1: PFC data 
currentHemisphere = 'MeanNE';
fig1 = figure('Name','PFC SST');

% REST
subplot(2,3,1); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanNE.Rest_Mean, data.Water.Day2.GroupStats.MeanNE.Rest_Mean, ...
     data.Water.Day3.GroupStats.MeanNE.Rest_Mean, data.Water.Day4.GroupStats.MeanNE.Rest_Mean, ...
     data.Water.Day5.GroupStats.MeanNE.Rest_Mean, data.Water.Day6.GroupStats.MeanNE.Rest_Mean], ...
    [data.Water.Day1.GroupStats.MeanNE.Rest_SEM, data.Water.Day2.GroupStats.MeanNE.Rest_SEM, ...
     data.Water.Day3.GroupStats.MeanNE.Rest_SEM, data.Water.Day4.GroupStats.MeanNE.Rest_SEM, ...
     data.Water.Day5.GroupStats.MeanNE.Rest_SEM, data.Water.Day6.GroupStats.MeanNE.Rest_SEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanNE.Rest_Mean, data.Alcohol.Day2.GroupStats.MeanNE.Rest_Mean, ...
     data.Alcohol.Day3.GroupStats.MeanNE.Rest_Mean, data.Alcohol.Day4.GroupStats.MeanNE.Rest_Mean, ...
     data.Alcohol.Day5.GroupStats.MeanNE.Rest_Mean, data.Alcohol.Day6.GroupStats.MeanNE.Rest_Mean], ...
    [data.Alcohol.Day1.GroupStats.MeanNE.Rest_SEM, data.Alcohol.Day2.GroupStats.MeanNE.Rest_SEM, ...
     data.Alcohol.Day3.GroupStats.MeanNE.Rest_SEM, data.Alcohol.Day4.GroupStats.MeanNE.Rest_SEM, ...
     data.Alcohol.Day5.GroupStats.MeanNE.Rest_SEM, data.Alcohol.Day6.GroupStats.MeanNE.Rest_SEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('Rest - PFC'); xticks(1:6); xticklabels(days); ylabel('MeanGFP SST(%)');
xlim([0.5 6.5])
ylim([-0.3 0.11])


% WHISK
subplot(2,3,2); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanNE.Whisk_Mean, data.Water.Day2.GroupStats.MeanNE.Whisk_Mean, ...
     data.Water.Day3.GroupStats.MeanNE.Whisk_Mean, data.Water.Day4.GroupStats.MeanNE.Whisk_Mean, ...
     data.Water.Day5.GroupStats.MeanNE.Whisk_Mean, data.Water.Day6.GroupStats.MeanNE.Whisk_Mean], ...
    [data.Water.Day1.GroupStats.MeanNE.Whisk_SEM, data.Water.Day2.GroupStats.MeanNE.Whisk_SEM, ...
     data.Water.Day3.GroupStats.MeanNE.Whisk_SEM, data.Water.Day4.GroupStats.MeanNE.Whisk_SEM, ...
     data.Water.Day5.GroupStats.MeanNE.Whisk_SEM, data.Water.Day6.GroupStats.MeanNE.Whisk_SEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanNE.Whisk_Mean, data.Alcohol.Day2.GroupStats.MeanNE.Whisk_Mean, ...
     data.Alcohol.Day3.GroupStats.MeanNE.Whisk_Mean, data.Alcohol.Day4.GroupStats.MeanNE.Whisk_Mean, ...
     data.Alcohol.Day5.GroupStats.MeanNE.Whisk_Mean, data.Alcohol.Day6.GroupStats.MeanNE.Whisk_Mean], ...
    [data.Alcohol.Day1.GroupStats.MeanNE.Whisk_SEM, data.Alcohol.Day2.GroupStats.MeanNE.Whisk_SEM, ...
     data.Alcohol.Day3.GroupStats.MeanNE.Whisk_SEM, data.Alcohol.Day4.GroupStats.MeanNE.Whisk_SEM, ...
     data.Alcohol.Day5.GroupStats.MeanNE.Whisk_SEM, data.Alcohol.Day6.GroupStats.MeanNE.Whisk_SEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('Whisk - PFC'); xticks(1:6); xticklabels(days); ylabel('MeanGFP SST(%)');
xlim([0.5 6.5])
ylim([-0.2 1.2])

% STIM 
subplot(2,3,3); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanNE.Stim_Mean, data.Water.Day2.GroupStats.MeanNE.Stim_Mean, ...
     data.Water.Day3.GroupStats.MeanNE.Stim_Mean, data.Water.Day4.GroupStats.MeanNE.Stim_Mean, ...
     data.Water.Day5.GroupStats.MeanNE.Stim_Mean, data.Water.Day6.GroupStats.MeanNE.Stim_Mean], ...
    [data.Water.Day1.GroupStats.MeanNE.Stim_SEM, data.Water.Day2.GroupStats.MeanNE.Stim_SEM, ...
     data.Water.Day3.GroupStats.MeanNE.Stim_SEM, data.Water.Day4.GroupStats.MeanNE.Stim_SEM, ...
     data.Water.Day5.GroupStats.MeanNE.Stim_SEM, data.Water.Day6.GroupStats.MeanNE.Stim_SEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanNE.Stim_Mean, data.Alcohol.Day2.GroupStats.MeanNE.Stim_Mean, ...
     data.Alcohol.Day3.GroupStats.MeanNE.Stim_Mean, data.Alcohol.Day4.GroupStats.MeanNE.Stim_Mean, ...
     data.Alcohol.Day5.GroupStats.MeanNE.Stim_Mean, data.Alcohol.Day6.GroupStats.MeanNE.Stim_Mean], ...
    [data.Alcohol.Day1.GroupStats.MeanNE.Stim_SEM, data.Alcohol.Day2.GroupStats.MeanNE.Stim_SEM, ...
     data.Alcohol.Day3.GroupStats.MeanNE.Stim_SEM, data.Alcohol.Day4.GroupStats.MeanNE.Stim_SEM, ...
     data.Alcohol.Day5.GroupStats.MeanNE.Stim_SEM, data.Alcohol.Day6.GroupStats.MeanNE.Stim_SEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('Stim - PFC'); xticks(1:6); xticklabels(days); ylabel('MeanGFP SST(%)');
xlim([0.5 6.5])
ylim([0.2 1.6])

% NREM 
subplot(2,3,4); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanNE.NREM_Mean, data.Water.Day2.GroupStats.MeanNE.NREM_Mean, ...
     data.Water.Day3.GroupStats.MeanNE.NREM_Mean, data.Water.Day4.GroupStats.MeanNE.NREM_Mean, ...
     data.Water.Day5.GroupStats.MeanNE.NREM_Mean, data.Water.Day6.GroupStats.MeanNE.NREM_Mean], ...
    [data.Water.Day1.GroupStats.MeanNE.NREM_SEM, data.Water.Day2.GroupStats.MeanNE.NREM_SEM, ...
     data.Water.Day3.GroupStats.MeanNE.NREM_SEM, data.Water.Day4.GroupStats.MeanNE.NREM_SEM, ...
     data.Water.Day5.GroupStats.MeanNE.NREM_SEM, data.Water.Day6.GroupStats.MeanNE.NREM_SEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanNE.NREM_Mean, data.Alcohol.Day2.GroupStats.MeanNE.NREM_Mean, ...
     data.Alcohol.Day3.GroupStats.MeanNE.NREM_Mean, data.Alcohol.Day4.GroupStats.MeanNE.NREM_Mean, ...
     data.Alcohol.Day5.GroupStats.MeanNE.NREM_Mean, data.Alcohol.Day6.GroupStats.MeanNE.NREM_Mean], ...
    [data.Alcohol.Day1.GroupStats.MeanNE.NREM_SEM, data.Alcohol.Day2.GroupStats.MeanNE.NREM_SEM, ...
     data.Alcohol.Day3.GroupStats.MeanNE.NREM_SEM, data.Alcohol.Day4.GroupStats.MeanNE.NREM_SEM, ...
     data.Alcohol.Day5.GroupStats.MeanNE.NREM_SEM, data.Alcohol.Day6.GroupStats.MeanNE.NREM_SEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('NREM - PFC'); xticks(1:6); xticklabels(days); ylabel('MeanGFP SST(%)'); 
xlim([0.5 6.5])
ylim([-0.4 0.4])

% REM 
subplot(2,3,5); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanNE.REM_Mean, data.Water.Day2.GroupStats.MeanNE.REM_Mean, ...
     data.Water.Day3.GroupStats.MeanNE.REM_Mean, data.Water.Day4.GroupStats.MeanNE.REM_Mean, ...
     data.Water.Day5.GroupStats.MeanNE.REM_Mean, data.Water.Day6.GroupStats.MeanNE.REM_Mean], ...
    [data.Water.Day1.GroupStats.MeanNE.REM_SEM, data.Water.Day2.GroupStats.MeanNE.REM_SEM, ...
     data.Water.Day3.GroupStats.MeanNE.REM_SEM, data.Water.Day4.GroupStats.MeanNE.REM_SEM, ...
     data.Water.Day5.GroupStats.MeanNE.REM_SEM, data.Water.Day6.GroupStats.MeanNE.REM_SEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanNE.REM_Mean, data.Alcohol.Day2.GroupStats.MeanNE.REM_Mean, ...
     data.Alcohol.Day3.GroupStats.MeanNE.REM_Mean, data.Alcohol.Day4.GroupStats.MeanNE.REM_Mean, ...
     data.Alcohol.Day5.GroupStats.MeanNE.REM_Mean, data.Alcohol.Day6.GroupStats.MeanNE.REM_Mean], ...
    [data.Alcohol.Day1.GroupStats.MeanNE.REM_SEM, data.Alcohol.Day2.GroupStats.MeanNE.REM_SEM, ...
     data.Alcohol.Day3.GroupStats.MeanNE.REM_SEM, data.Alcohol.Day4.GroupStats.MeanNE.REM_SEM, ...
     data.Alcohol.Day5.GroupStats.MeanNE.REM_SEM, data.Alcohol.Day6.GroupStats.MeanNE.REM_SEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('REM - PFC'); xticks(1:6); xticklabels(days); ylabel('MeanGFP SST(%)'); 
xlim([0.5 6.5])
ylim([-0 1.5])

sgtitle('PFC SST - Water vs Alcohol - All Behaviors');
legend({'Water','Alcohol'});
%% Figure 2: S1BF data 
currentHemisphere = 'MeanACh';
fig2 = figure('Name','S1BF SST');

% REST 
subplot(2,3,1); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanACh.Rest_Mean, data.Water.Day2.GroupStats.MeanACh.Rest_Mean, ...
     data.Water.Day3.GroupStats.MeanACh.Rest_Mean, data.Water.Day4.GroupStats.MeanACh.Rest_Mean, ...
     data.Water.Day5.GroupStats.MeanACh.Rest_Mean, data.Water.Day6.GroupStats.MeanACh.Rest_Mean], ...
    [data.Water.Day1.GroupStats.MeanACh.Rest_SEM, data.Water.Day2.GroupStats.MeanACh.Rest_SEM, ...
     data.Water.Day3.GroupStats.MeanACh.Rest_SEM, data.Water.Day4.GroupStats.MeanACh.Rest_SEM, ...
     data.Water.Day5.GroupStats.MeanACh.Rest_SEM, data.Water.Day6.GroupStats.MeanACh.Rest_SEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanACh.Rest_Mean, data.Alcohol.Day2.GroupStats.MeanACh.Rest_Mean, ...
     data.Alcohol.Day3.GroupStats.MeanACh.Rest_Mean, data.Alcohol.Day4.GroupStats.MeanACh.Rest_Mean, ...
     data.Alcohol.Day5.GroupStats.MeanACh.Rest_Mean, data.Alcohol.Day6.GroupStats.MeanACh.Rest_Mean], ...
    [data.Alcohol.Day1.GroupStats.MeanACh.Rest_SEM, data.Alcohol.Day2.GroupStats.MeanACh.Rest_SEM, ...
     data.Alcohol.Day3.GroupStats.MeanACh.Rest_SEM, data.Alcohol.Day4.GroupStats.MeanACh.Rest_SEM, ...
     data.Alcohol.Day5.GroupStats.MeanACh.Rest_SEM, data.Alcohol.Day6.GroupStats.MeanACh.Rest_SEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('Rest - S1BF'); xticks(1:6); xticklabels(days); ylabel('MeanGFP SST(%)');
xlim([0.5 6.5])
ylim([-0.3 0.6])

% WHISK 
subplot(2,3,2); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanACh.Whisk_Mean, data.Water.Day2.GroupStats.MeanACh.Whisk_Mean, ...
     data.Water.Day3.GroupStats.MeanACh.Whisk_Mean, data.Water.Day4.GroupStats.MeanACh.Whisk_Mean, ...
     data.Water.Day5.GroupStats.MeanACh.Whisk_Mean, data.Water.Day6.GroupStats.MeanACh.Whisk_Mean], ...
    [data.Water.Day1.GroupStats.MeanACh.Whisk_SEM, data.Water.Day2.GroupStats.MeanACh.Whisk_SEM, ...
     data.Water.Day3.GroupStats.MeanACh.Whisk_SEM, data.Water.Day4.GroupStats.MeanACh.Whisk_SEM, ...
     data.Water.Day5.GroupStats.MeanACh.Whisk_SEM, data.Water.Day6.GroupStats.MeanACh.Whisk_SEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanACh.Whisk_Mean, data.Alcohol.Day2.GroupStats.MeanACh.Whisk_Mean, ...
     data.Alcohol.Day3.GroupStats.MeanACh.Whisk_Mean, data.Alcohol.Day4.GroupStats.MeanACh.Whisk_Mean, ...
     data.Alcohol.Day5.GroupStats.MeanACh.Whisk_Mean, data.Alcohol.Day6.GroupStats.MeanACh.Whisk_Mean], ...
    [data.Alcohol.Day1.GroupStats.MeanACh.Whisk_SEM, data.Alcohol.Day2.GroupStats.MeanACh.Whisk_SEM, ...
     data.Alcohol.Day3.GroupStats.MeanACh.Whisk_SEM, data.Alcohol.Day4.GroupStats.MeanACh.Whisk_SEM, ...
     data.Alcohol.Day5.GroupStats.MeanACh.Whisk_SEM, data.Alcohol.Day6.GroupStats.MeanACh.Whisk_SEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('Whisk - S1BF'); xticks(1:6); xticklabels(days); ylabel('MeanGFP SST(%)');
xlim([0.5 6.5])
ylim([-0.3 2])

% STIM 
subplot(2,3,3); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanACh.Stim_Mean, data.Water.Day2.GroupStats.MeanACh.Stim_Mean, ...
     data.Water.Day3.GroupStats.MeanACh.Stim_Mean, data.Water.Day4.GroupStats.MeanACh.Stim_Mean, ...
     data.Water.Day5.GroupStats.MeanACh.Stim_Mean, data.Water.Day6.GroupStats.MeanACh.Stim_Mean], ...
    [data.Water.Day1.GroupStats.MeanACh.Stim_SEM, data.Water.Day2.GroupStats.MeanACh.Stim_SEM, ...
     data.Water.Day3.GroupStats.MeanACh.Stim_SEM, data.Water.Day4.GroupStats.MeanACh.Stim_SEM, ...
     data.Water.Day5.GroupStats.MeanACh.Stim_SEM, data.Water.Day6.GroupStats.MeanACh.Stim_SEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanACh.Stim_Mean, data.Alcohol.Day2.GroupStats.MeanACh.Stim_Mean, ...
     data.Alcohol.Day3.GroupStats.MeanACh.Stim_Mean, data.Alcohol.Day4.GroupStats.MeanACh.Stim_Mean, ...
     data.Alcohol.Day5.GroupStats.MeanACh.Stim_Mean, data.Alcohol.Day6.GroupStats.MeanACh.Stim_Mean], ...
    [data.Alcohol.Day1.GroupStats.MeanACh.Stim_SEM, data.Alcohol.Day2.GroupStats.MeanACh.Stim_SEM, ...
     data.Alcohol.Day3.GroupStats.MeanACh.Stim_SEM, data.Alcohol.Day4.GroupStats.MeanACh.Stim_SEM, ...
     data.Alcohol.Day5.GroupStats.MeanACh.Stim_SEM, data.Alcohol.Day6.GroupStats.MeanACh.Stim_SEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('Stim - S1BF'); xticks(1:6); xticklabels(days); ylabel('MeanGFP SST(%)'); 
xlim([0.5 6.5])
ylim([-0.3 2])

% NREM 
subplot(2,3,4); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanACh.NREM_Mean, data.Water.Day2.GroupStats.MeanACh.NREM_Mean, ...
     data.Water.Day3.GroupStats.MeanACh.NREM_Mean, data.Water.Day4.GroupStats.MeanACh.NREM_Mean, ...
     data.Water.Day5.GroupStats.MeanACh.NREM_Mean, data.Water.Day6.GroupStats.MeanACh.NREM_Mean], ...
    [data.Water.Day1.GroupStats.MeanACh.NREM_SEM, data.Water.Day2.GroupStats.MeanACh.NREM_SEM, ...
     data.Water.Day3.GroupStats.MeanACh.NREM_SEM, data.Water.Day4.GroupStats.MeanACh.NREM_SEM, ...
     data.Water.Day5.GroupStats.MeanACh.NREM_SEM, data.Water.Day6.GroupStats.MeanACh.NREM_SEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanACh.NREM_Mean, data.Alcohol.Day2.GroupStats.MeanACh.NREM_Mean, ...
     data.Alcohol.Day3.GroupStats.MeanACh.NREM_Mean, data.Alcohol.Day4.GroupStats.MeanACh.NREM_Mean, ...
     data.Alcohol.Day5.GroupStats.MeanACh.NREM_Mean, data.Alcohol.Day6.GroupStats.MeanACh.NREM_Mean], ...
    [data.Alcohol.Day1.GroupStats.MeanACh.NREM_SEM, data.Alcohol.Day2.GroupStats.MeanACh.NREM_SEM, ...
     data.Alcohol.Day3.GroupStats.MeanACh.NREM_SEM, data.Alcohol.Day4.GroupStats.MeanACh.NREM_SEM, ...
     data.Alcohol.Day5.GroupStats.MeanACh.NREM_SEM, data.Alcohol.Day6.GroupStats.MeanACh.NREM_SEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('NREM - S1BF'); xticks(1:6); xticklabels(days); ylabel('MeanGFP SST(%)');
xlim([0.5 6.5])
ylim([-0.3 1.7])

% REM 
subplot(2,3,5); hold on;
errorbar(1:6, ...
    [data.Water.Day1.GroupStats.MeanACh.REM_Mean, data.Water.Day2.GroupStats.MeanACh.REM_Mean, ...
     data.Water.Day3.GroupStats.MeanACh.REM_Mean, data.Water.Day4.GroupStats.MeanACh.REM_Mean, ...
     data.Water.Day5.GroupStats.MeanACh.REM_Mean, data.Water.Day6.GroupStats.MeanACh.REM_Mean], ...
    [data.Water.Day1.GroupStats.MeanACh.REM_SEM, data.Water.Day2.GroupStats.MeanACh.REM_SEM, ...
     data.Water.Day3.GroupStats.MeanACh.REM_SEM, data.Water.Day4.GroupStats.MeanACh.REM_SEM, ...
     data.Water.Day5.GroupStats.MeanACh.REM_SEM, data.Water.Day6.GroupStats.MeanACh.REM_SEM], ...
    '-o','Color',waterColor,'LineWidth',2);
errorbar(1:6, ...
    [data.Alcohol.Day1.GroupStats.MeanACh.REM_Mean, data.Alcohol.Day2.GroupStats.MeanACh.REM_Mean, ...
     data.Alcohol.Day3.GroupStats.MeanACh.REM_Mean, data.Alcohol.Day4.GroupStats.MeanACh.REM_Mean, ...
     data.Alcohol.Day5.GroupStats.MeanACh.REM_Mean, data.Alcohol.Day6.GroupStats.MeanACh.REM_Mean], ...
    [data.Alcohol.Day1.GroupStats.MeanACh.REM_SEM, data.Alcohol.Day2.GroupStats.MeanACh.REM_SEM, ...
     data.Alcohol.Day3.GroupStats.MeanACh.REM_SEM, data.Alcohol.Day4.GroupStats.MeanACh.REM_SEM, ...
     data.Alcohol.Day5.GroupStats.MeanACh.REM_SEM, data.Alcohol.Day6.GroupStats.MeanACh.REM_SEM], ...
    '-o','Color',alcoholColor,'LineWidth',2);
title('REM - S1BF'); xticks(1:6); xticklabels(days); ylabel('MeanGFP SST(%)');
xlim([0.5 6.5])
ylim([-0.3 3.0])

sgtitle('S1BF SST - Water vs Alcohol - All Behaviors');
legend({'Water','Alcohol'});


%% Figure 3: Bar graph with individual data points PFC 
currentHemisphere = 'MeanNE';
behaviorList = {'Rest','Whisk','Stim','NREM','REM'};
days = {'Day1','Day2','Day3','Day4','Day5','Day6'};
x = 1:6;
xOffset = 0.15;

fig3 = figure('Name','PFC SST - All Behaviors - Group + Individual');


for b = 1:length(behaviorList)
    currentBehavior = behaviorList{b};
    subplot(2,3,b); hold on;
    
 % WATER MEAN AND SEM
    waterMean = [data.Water.Day1.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                 data.Water.Day2.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                 data.Water.Day3.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                 data.Water.Day4.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                 data.Water.Day5.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                 data.Water.Day6.GroupStats.(currentHemisphere).([currentBehavior '_Mean'])];

    waterSEM  = [data.Water.Day1.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                 data.Water.Day2.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                 data.Water.Day3.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                 data.Water.Day4.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                 data.Water.Day5.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                 data.Water.Day6.GroupStats.(currentHemisphere).([currentBehavior '_SEM'])];

    bar(x - xOffset, waterMean, 0.3, 'FaceColor', waterColor, 'EdgeColor', 'none');
    errorbar(x - xOffset, waterMean, waterSEM, 'k.', 'LineWidth', 1.5, 'CapSize', 10);

% ALCOHOL MEAN AND SEM
    alcoholMean = [data.Alcohol.Day1.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                   data.Alcohol.Day2.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                   data.Alcohol.Day3.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                   data.Alcohol.Day4.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                   data.Alcohol.Day5.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                   data.Alcohol.Day6.GroupStats.(currentHemisphere).([currentBehavior '_Mean'])];

    alcoholSEM  = [data.Alcohol.Day1.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                   data.Alcohol.Day2.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                   data.Alcohol.Day3.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                   data.Alcohol.Day4.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                   data.Alcohol.Day5.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                   data.Alcohol.Day6.GroupStats.(currentHemisphere).([currentBehavior '_SEM'])];

    bar(x + xOffset, alcoholMean, 0.3, 'FaceColor', alcoholColor, 'EdgeColor', 'none');
    errorbar(x + xOffset, alcoholMean, alcoholSEM, 'k.', 'LineWidth', 1.5, 'CapSize', 10); 

% SCATTER PLOT: WATER MICE
    for d = 1:6
        mouseIDs = fieldnames(data.Water.(days{d}));
        mouseIDs(strcmp(mouseIDs,'GroupStats')) = [];
        values = [];
        for aa = 1:length(mouseIDs)
            if isfield(data.Water.(days{d}).(mouseIDs{aa}).MeanGFP.(currentHemisphere), [currentBehavior '_Mean'])
                values(end+1) = data.Water.(days{d}).(mouseIDs{aa}).MeanGFP.(currentHemisphere).([currentBehavior '_Mean']);
            end
        end
        scatter(repmat(d - xOffset, 1, length(values)), values, 40, 'r', 'filled', 'jitter', 'on', 'jitterAmount', 0.1);
    end

% SCATTER PLOT: ALCOHOL MICE 
    for d = 1:6
        mouseIDs = fieldnames(data.Alcohol.(days{d}));
        mouseIDs(strcmp(mouseIDs,'GroupStats')) = [];
        values = [];
        for aa = 1:length(mouseIDs)
            if isfield(data.Alcohol.(days{d}).(mouseIDs{aa}).MeanGFP.(currentHemisphere), [currentBehavior '_Mean'])
                values(end+1) = data.Alcohol.(days{d}).(mouseIDs{aa}).MeanGFP.(currentHemisphere).([currentBehavior '_Mean']);
            end
        end
        scatter(repmat(d + xOffset, 1, length(values)), values, 40, [0.6 0.6 0.6], 'filled', 'jitter', 'on', 'jitterAmount', 0.1);
    end

    title([currentBehavior ' - PFC']);
    xticks(1:6);
    xticklabels({'BL','DID1','DID2','DID3','DID4','Post-alcohol'});
    ylabel('MeanGFP SST(%)');
    xlim([0.5 6.5])
end

sgtitle('PFC SST- All Behaviors - Group + Individual');
legend({'Water mean','Water SEM', 'Alcohol Mean', 'Alcohol SEM'});

%% Figure 4: Bar graph with individual data points PFC 
currentHemisphere = 'MeanACh';
behaviorList = {'Rest','Whisk','Stim','NREM','REM'};
days = {'Day1','Day2','Day3','Day4','Day5','Day6'};
x = 1:6;
xOffset = 0.15;

fig4 = figure('Name','S1BF SST - All Behaviors - Group + Individual');


for b = 1:length(behaviorList)
    currentBehavior = behaviorList{b};
    subplot(2,3,b); hold on;
    
 % WATER MEAN AND SEM
    waterMean = [data.Water.Day1.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                 data.Water.Day2.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                 data.Water.Day3.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                 data.Water.Day4.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                 data.Water.Day5.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                 data.Water.Day6.GroupStats.(currentHemisphere).([currentBehavior '_Mean'])];

    waterSEM  = [data.Water.Day1.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                 data.Water.Day2.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                 data.Water.Day3.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                 data.Water.Day4.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                 data.Water.Day5.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                 data.Water.Day6.GroupStats.(currentHemisphere).([currentBehavior '_SEM'])];

    bar(x - xOffset, waterMean, 0.3, 'FaceColor', waterColor, 'EdgeColor', 'none');
    errorbar(x - xOffset, waterMean, waterSEM, 'k.', 'LineWidth', 1.5, 'CapSize', 10);

% ALCOHOL MEAN AND SEM
    alcoholMean = [data.Alcohol.Day1.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                   data.Alcohol.Day2.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                   data.Alcohol.Day3.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                   data.Alcohol.Day4.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                   data.Alcohol.Day5.GroupStats.(currentHemisphere).([currentBehavior '_Mean']), ...
                   data.Alcohol.Day6.GroupStats.(currentHemisphere).([currentBehavior '_Mean'])];

    alcoholSEM  = [data.Alcohol.Day1.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                   data.Alcohol.Day2.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                   data.Alcohol.Day3.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                   data.Alcohol.Day4.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                   data.Alcohol.Day5.GroupStats.(currentHemisphere).([currentBehavior '_SEM']), ...
                   data.Alcohol.Day6.GroupStats.(currentHemisphere).([currentBehavior '_SEM'])];

    bar(x + xOffset, alcoholMean, 0.3, 'FaceColor', alcoholColor, 'EdgeColor', 'none');
    errorbar(x + xOffset, alcoholMean, alcoholSEM, 'k.', 'LineWidth', 1.5, 'CapSize', 10); 

% SCATTER PLOT: WATER MICE
    for d = 1:6
        mouseIDs = fieldnames(data.Water.(days{d}));
        mouseIDs(strcmp(mouseIDs,'GroupStats')) = [];
        values = [];
        for aa = 1:length(mouseIDs)
            if isfield(data.Water.(days{d}).(mouseIDs{aa}).MeanGFP.(currentHemisphere), [currentBehavior '_Mean'])
                values(end+1) = data.Water.(days{d}).(mouseIDs{aa}).MeanGFP.(currentHemisphere).([currentBehavior '_Mean']);
            end
        end
        scatter(repmat(d - xOffset, 1, length(values)), values, 40, 'r', 'filled', 'jitter', 'on', 'jitterAmount', 0.1);
    end

% SCATTER PLOT: ALCOHOL MICE 
    for d = 1:6
        mouseIDs = fieldnames(data.Alcohol.(days{d}));
        mouseIDs(strcmp(mouseIDs,'GroupStats')) = [];
        values = [];
        for aa = 1:length(mouseIDs)
            if isfield(data.Alcohol.(days{d}).(mouseIDs{aa}).MeanGFP.(currentHemisphere), [currentBehavior '_Mean'])
                values(end+1) = data.Alcohol.(days{d}).(mouseIDs{aa}).MeanGFP.(currentHemisphere).([currentBehavior '_Mean']);
            end
        end
        scatter(repmat(d + xOffset, 1, length(values)), values, 40, [0.6 0.6 0.6], 'filled', 'jitter', 'on', 'jitterAmount', 0.1);
    end

    title([currentBehavior ' - S1BF']);
    xticks(1:6);
    xticklabels({'BL','DID1','DID2','DID3','DID4','Post-alcohol'});
    ylabel('MeanGFP SST(%)');
    xlim([0.5 6.5])
end

sgtitle('S1BF SST- All Behaviors - Group + Individual');
legend({'Water mean','Water SEM', 'Alcohol Mean', 'Alcohol SEM'});
%% Save figure
if saveState == true
    dirpath = [rootFolder delim 'MATLAB Figures Water vs Alcohol' delim 'MeanGFP'];
    if ~exist(dirpath,'dir')
        mkdir(dirpath);
    end
    savefig(fig1, fullfile(dirpath, 'Mean GFP SST PFC - All Behaviors'));
    savefig(fig2, fullfile(dirpath, 'Mean GFP SST S1BF - All Behaviors'));
    savefig(fig3, fullfile(dirpath, 'Individual data points Mean GFP SST PFC - All Behaviors'));
    savefig(fig4, fullfile(dirpath, 'Individual data points Mean GFP SST S1BF - All Behaviors'));
end

